module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      animation: {
        'spin-slow': 'spin 1.5s linear infinite',
        },
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        'auoBlue': '#005087', 
        'smartBlue': '#64dcf0',
        'energeticYellow': '#ffe664',
        'innovativePurple': '#b491d7',
        'sustainableGreen': '#87dc64',
        'darkBlue':'#147891',
        'darkYellow':'#E6A50F',
        'darkPurple':'#643C96',
        'darkGreen':'#328732',
        'darkRed':'#E65F5A',
        'darkBrown':'#785A46',
        'lightBlue':'#BEE6E1',
        'lightYellow':'#FFF0B4',
        'lightPurple':'#D7B4E1',
        'lightGreen':'#D2F09B',
        'lightRed':'#FFC8AA',
        'lightBrown':'#D2B496',
        'gray':{
          0: '#414141',
          1: '#646464',
          2: '#969696',
          3: '#c8c8c8',
          4: '#e1e1e1',
          5: '#f0f0f0',
          6: '#f5f5f5',
        },
        'white': '#ffffff',
        'maskColor': '#003c6599',
        'silver': '#ecebff',
        'bubble-gum': '#ff77e9',
        'bermuda': '#78dcca',     
        
        
            },
      },
      
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        auotheme: {          
          "primary": "#005087",
          "secondary": "#27C7D7",
          "accent": "#A17DCA",
          "neutral": "#383735",
          "base-100": "#f6f6f6",
          "info": "#FFE665",
          "success": "#8DE26A",
          "warning": "#efa748",
          "error": "#db2777",
        
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
